# Form implementation generated from reading ui file 'd:\Code\Python\OSCinput\main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 150)
        MainWindow.setMinimumSize(QtCore.QSize(500, 150))
        MainWindow.setMaximumSize(QtCore.QSize(500, 150))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tx_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.tx_input.setGeometry(QtCore.QRect(10, 10, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tx_input.setFont(font)
        self.tx_input.setText("")
        self.tx_input.setObjectName("tx_input")
        self.bt_open = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_open.setGeometry(QtCore.QRect(10, 40, 241, 101))
        self.bt_open.setObjectName("bt_open")
        self.bt_close = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_close.setGeometry(QtCore.QRect(250, 40, 241, 101))
        self.bt_close.setObjectName("bt_close")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OSC输入框"))
        self.bt_open.setText(_translate("MainWindow", "打开键盘"))
        self.bt_close.setText(_translate("MainWindow", "发送"))
